### ISSUE TITLE
I can't Test the RBXLegacy launcher on Visual Studio

### ISSUE THREAD

**Issue by AndrewChief** [Bitl/RBXLegacy-src#18]
http://prntscr.com/g9t9b1
http://prntscr.com/g9t9en

Hello, I fixed 7 errors yet, read below.

Correction: 
- You needed to put geardir instead of hatdir like that: http://prntscr.com/g9ta8y
- Instead of 'CustomGear3' http://prntscr.com/g9tav4, you needed to write Custom_Gear3 http://prntscr.com/g9tajg

The only issues to fix right now are here: http://prntscr.com/g9tb8u

**Comment by Swirln** [comment]
We have fixed the CustomGear3 issues but thank you for reporting the other issues you have found. We are on it
